### PR TITLE
Do subsasgn works

### PR DESCRIPTION
**Pull request by latot**

### CODE REVIEW

**Comment by genuinelucifer** [comment]
Hi @lalot.
Please go through travis logs.. There are a lot of errors "class not found: sym"!!
Is it be because of some path issues? Did the tests work on your PC?

**Comment by latot** [comment]
Hi, sadly for some reason that only happen in travis, if you check travis from your main pr this happen too, locally tests works, (except isa tests and maybe others), travis use octave-4.0.2 while we are using 4.2.0-rc2, so i think its possible classdef don't was improved in that version, for now i think we can do a new section in `.travis.yml` to compile octave and test octsympy from there, but i really don't like this idea because is too slow, so maybe request to @mtmiller to send a new octave version to his PPA (https://launchpad.net/~mtmiller/+archive/ubuntu/octave) and then use it from travis.

Thx. Cya.

**Comment by genuinelucifer** [comment]
Oh yes. I remember this now.
.
Just one more thing, could you please squash the commits (or at least the first 2 commits into 1)?
If you want I can send you the commands to do so in git..

**Comment by latot** [comment]
Okidokis, ready!

**Pull request merged**
